/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WorkflowsExplanationLetterRouteImport } from './routes/workflows/explanation-letter'
import { Route as WorkflowsRespondToNoticeRouteImport } from './routes/workflows/respond-to-notice'
import { Route as WorkflowsSupportingDocumentsRouteImport } from './routes/workflows/supporting-documents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsExplanationLetterRoute =
  WorkflowsExplanationLetterRouteImport.update({
    id: '/workflows/explanation-letter',
    path: '/workflows/explanation-letter',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsRespondToNoticeRoute =
  WorkflowsRespondToNoticeRouteImport.update({
    id: '/workflows/respond-to-notice',
    path: '/workflows/respond-to-notice',
    getParentRoute: () => rootRouteImport,
  } as any)
const WorkflowsSupportingDocumentsRoute =
  WorkflowsSupportingDocumentsRouteImport.update({
    id: '/workflows/supporting-documents',
    path: '/workflows/supporting-documents',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/workflows/explanation-letter': typeof WorkflowsExplanationLetterRoute
  '/workflows/respond-to-notice': typeof WorkflowsRespondToNoticeRoute
  '/workflows/supporting-documents': typeof WorkflowsSupportingDocumentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/workflows/explanation-letter': typeof WorkflowsExplanationLetterRoute
  '/workflows/respond-to-notice': typeof WorkflowsRespondToNoticeRoute
  '/workflows/supporting-documents': typeof WorkflowsSupportingDocumentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/workflows/explanation-letter': typeof WorkflowsExplanationLetterRoute
  '/workflows/respond-to-notice': typeof WorkflowsRespondToNoticeRoute
  '/workflows/supporting-documents': typeof WorkflowsSupportingDocumentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/workflows/explanation-letter'
    | '/workflows/respond-to-notice'
    | '/workflows/supporting-documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/workflows/explanation-letter'
    | '/workflows/respond-to-notice'
    | '/workflows/supporting-documents'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/terms'
    | '/workflows/explanation-letter'
    | '/workflows/respond-to-notice'
    | '/workflows/supporting-documents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WorkflowsExplanationLetterRoute: typeof WorkflowsExplanationLetterRoute
  WorkflowsRespondToNoticeRoute: typeof WorkflowsRespondToNoticeRoute
  WorkflowsSupportingDocumentsRoute: typeof WorkflowsSupportingDocumentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/explanation-letter': {
      id: '/workflows/explanation-letter'
      path: '/workflows/explanation-letter'
      fullPath: '/workflows/explanation-letter'
      preLoaderRoute: typeof WorkflowsExplanationLetterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/respond-to-notice': {
      id: '/workflows/respond-to-notice'
      path: '/workflows/respond-to-notice'
      fullPath: '/workflows/respond-to-notice'
      preLoaderRoute: typeof WorkflowsRespondToNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/supporting-documents': {
      id: '/workflows/supporting-documents'
      path: '/workflows/supporting-documents'
      fullPath: '/workflows/supporting-documents'
      preLoaderRoute: typeof WorkflowsSupportingDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WorkflowsExplanationLetterRoute: WorkflowsExplanationLetterRoute,
  WorkflowsRespondToNoticeRoute: WorkflowsRespondToNoticeRoute,
  WorkflowsSupportingDocumentsRoute: WorkflowsSupportingDocumentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
